// src/lib/mock-data.js
// Расширенный набор тестовых данных для имитации большого ассортимента интернет-магазина

const productMockData = [
	// Оригинальные позиции
	{
		id: 1,
		name: 'Карточки по математике 5-6 класс',
		price: 890,
		oldPrice: 1190,
		rating: 4.8,
		reviewCount: 124,
		imageSrc: '/images/products/math-cards.jpg',
		label: 'Хит продаж',
		subject: 'Математика',
		grade: '5-6 класс',
		cardType: 'Вопрос-ответ',
		quantity: 15,
		slug: 'kartochki-po-matematike-5-6-klass',
		number_of_cards: 50,
		description:
			'Комплект карточек по математике для 5-6 классов содержит основные формулы, определения и примеры решения задач.',
	},
	{
		id: 2,
		name: 'Карточки по физике ОГЭ',
		price: 950,
		oldPrice: null,
		rating: 4.5,
		reviewCount: 87,
		imageSrc: '/images/products/physics-cards.jpg',
		label: 'Новинка',
		subject: 'Физика',
		grade: '9 класс (ОГЭ)',
		cardType: 'Шпаргалки',
		quantity: 8,
		slug: 'kartochki-po-fizike-oge',
		number_of_cards: 40,
		description:
			'Карточки-шпаргалки с основными формулами и законами физики для подготовки к ОГЭ.',
	},
	{
		id: 3,
		name: 'Карточки по русскому языку ЕГЭ',
		price: 790,
		oldPrice: 990,
		rating: 4.7,
		reviewCount: 156,
		imageSrc: '/images/products/russian-cards.jpg',
		label: 'Скидка 20%',
		subject: 'Русский язык',
		grade: '11 класс (ЕГЭ)',
		cardType: 'Комбинированный',
		quantity: 12,
		slug: 'kartochki-po-russkomu-yazyku-ege',
		number_of_cards: 60,
		description:
			'Комбинированный набор карточек для подготовки к ЕГЭ по русскому языку с правилами, исключениями и примерами.',
	},
	{
		id: 4,
		name: 'Карточки по биологии 7-8 класс',
		price: 850,
		oldPrice: 1050,
		rating: 4.6,
		reviewCount: 92,
		imageSrc: '/images/products/biology-cards.jpg',
		label: null,
		subject: 'Биология',
		grade: '7-8 класс',
		cardType: 'Вопрос-ответ',
		quantity: 5,
		slug: 'kartochki-po-biologii-7-8-klass',
		number_of_cards: 45,
		description:
			'Карточки с вопросами и ответами для изучения основ биологии в 7-8 классах.',
	},
	{
		id: 5,
		name: 'Карточки по химии 8-9 класс',
		price: 920,
		oldPrice: null,
		rating: 4.4,
		reviewCount: 78,
		imageSrc: '/images/products/chemistry-cards.jpg',
		label: null,
		subject: 'Химия',
		grade: '8-9 класс',
		cardType: 'Шпаргалки',
		quantity: 2,
		slug: 'kartochki-po-khimii-8-9-klass',
		number_of_cards: 55,
		description:
			'Шпаргалки по химии с основными формулами, определениями и таблицей Менделеева.',
	},
	{
		id: 6,
		name: 'Карточки по истории ЕГЭ',
		price: 990,
		oldPrice: 1290,
		rating: 4.9,
		reviewCount: 142,
		imageSrc: '/images/products/history-cards.jpg',
		label: 'Топ продаж',
		subject: 'История',
		grade: '11 класс (ЕГЭ)',
		cardType: 'Комбинированный',
		quantity: 0,
		slug: 'kartochki-po-istorii-ege',
		number_of_cards: 70,
		description:
			'Комбинированный набор карточек для подготовки к ЕГЭ по истории с ключевыми датами, событиями и историческими личностями.',
	},
	{
		id: 7,
		name: 'Карточки по английскому языку 5-7 класс',
		price: 780,
		oldPrice: 920,
		rating: 4.7,
		reviewCount: 112,
		imageSrc: '/images/products/english-cards.jpg',
		label: 'Скидка 15%',
		subject: 'Английский язык',
		grade: '5-7 класс',
		cardType: 'Вопрос-ответ',
		quantity: 10,
		slug: 'kartochki-po-angliyskomu-yazyku-5-7-klass',
		number_of_cards: 60,
		description:
			'Карточки с вопросами и ответами для изучения английской грамматики и лексики.',
	},
	{
		id: 8,
		name: 'Карточки по литературе 10-11 класс',
		price: 860,
		oldPrice: null,
		rating: 4.6,
		reviewCount: 94,
		imageSrc: '/images/products/literature-cards.jpg',
		label: null,
		subject: 'Литература',
		grade: '10-11 класс',
		cardType: 'Шпаргалки',
		quantity: 7,
		slug: 'kartochki-po-literature-10-11-klass',
		number_of_cards: 50,
		description:
			'Шпаргалки по литературе с краткими содержаниями произведений, характеристиками героев и цитатами.',
	},
	{
		id: 9,
		name: 'Карточки по географии 6-7 класс',
		price: 760,
		oldPrice: 890,
		rating: 4.5,
		reviewCount: 82,
		imageSrc: '/images/products/geography-cards.jpg',
		label: null,
		subject: 'География',
		grade: '6-7 класс',
		cardType: 'Вопрос-ответ',
		quantity: 4,
		slug: 'kartochki-po-geografii-6-7-klass',
		number_of_cards: 40,
		description:
			'Карточки с вопросами и ответами для изучения географии в 6-7 классах, включая основы физической географии.',
	},
	{
		id: 10,
		name: 'Карточки по обществознанию ОГЭ',
		price: 880,
		oldPrice: 1080,
		rating: 4.8,
		reviewCount: 136,
		imageSrc: '/images/products/society-cards.jpg',
		label: 'Хит продаж',
		subject: 'Обществознание',
		grade: '9 класс (ОГЭ)',
		cardType: 'Комбинированный',
		quantity: 9,
		slug: 'kartochki-po-obshchestvoznaniyu-oge',
		number_of_cards: 65,
		description:
			'Комбинированный набор карточек для подготовки к ОГЭ по обществознанию с основными понятиями и терминами.',
	},
	{
		id: 11,
		name: 'Карточки по информатике 8-9 класс',
		price: 840,
		oldPrice: null,
		rating: 4.6,
		reviewCount: 98,
		imageSrc: '/images/products/informatics-cards.jpg',
		label: 'Новинка',
		subject: 'Информатика',
		grade: '8-9 класс',
		cardType: 'Шпаргалки',
		quantity: 1,
		slug: 'kartochki-po-informatike-8-9-klass',
		number_of_cards: 45,
		description:
			'Шпаргалки по информатике с алгоритмами, структурами данных и примерами кода.',
	},
	{
		id: 12,
		name: 'Карточки по геометрии 7-9 класс',
		price: 820,
		oldPrice: 950,
		rating: 4.7,
		reviewCount: 108,
		imageSrc: '/images/products/geometry-cards.jpg',
		label: 'Скидка 15%',
		subject: 'Геометрия',
		grade: '7-9 класс',
		cardType: 'Вопрос-ответ',
		quantity: 0,
		slug: 'kartochki-po-geometrii-7-9-klass',
		number_of_cards: 40,
		description:
			'Карточки с формулами, теоремами и задачами по планиметрии для учеников 7-9 классов.',
	},

	// Дополнительные карточки для расширения ассортимента

	// Математика (дополнительные карточки)
	{
		id: 13,
		name: 'Карточки по алгебре 7-9 класс',
		price: 870,
		oldPrice: 980,
		rating: 4.7,
		reviewCount: 115,
		imageSrc: '/images/products/algebra-cards.jpg',
		label: 'Скидка 10%',
		subject: 'Математика',
		grade: '7-9 класс',
		cardType: 'Вопрос-ответ',
		quantity: 8,
		slug: 'kartochki-po-algebre-7-9-klass',
		number_of_cards: 55,
		description:
			'Карточки по алгебре с формулами, графиками функций и методами решения уравнений для учеников 7-9 классов.',
	},
	{
		id: 14,
		name: 'Карточки по математике ЕГЭ (базовый уровень)',
		price: 950,
		oldPrice: 1100,
		rating: 4.9,
		reviewCount: 178,
		imageSrc: '/images/products/math-base-cards.jpg',
		label: 'Топ продаж',
		subject: 'Математика',
		grade: '11 класс (ЕГЭ)',
		cardType: 'Шпаргалки',
		quantity: 15,
		slug: 'kartochki-po-matematike-ege-bazovyy-uroven',
		number_of_cards: 60,
		description:
			'Шпаргалки для подготовки к ЕГЭ по математике базового уровня.',
	},
	{
		id: 15,
		name: 'Карточки по математике ЕГЭ (профильный уровень)',
		price: 1050,
		oldPrice: 1250,
		rating: 4.8,
		reviewCount: 195,
		imageSrc: '/images/products/math-prof-cards.jpg',
		label: 'Хит продаж',
		subject: 'Математика',
		grade: '11 класс (ЕГЭ)',
		cardType: 'Комбинированный',
		quantity: 7,
		slug: 'kartochki-po-matematike-ege-profilnyy-uroven',
		number_of_cards: 75,
		description:
			'Комбинированный набор карточек для подготовки к ЕГЭ по математике профильного уровня.',
	},
	{
		id: 16,
		name: 'Карточки по математике для начальной школы',
		price: 690,
		oldPrice: null,
		rating: 4.9,
		reviewCount: 203,
		imageSrc: '/images/products/math-primary-cards.jpg',
		label: 'Хит продаж',
		subject: 'Математика',
		grade: '1-4 класс',
		cardType: 'Вопрос-ответ',
		quantity: 25,
		slug: 'kartochki-po-matematike-dlya-nachalnoy-shkoly',
		number_of_cards: 40,
		description:
			'Карточки с основами арифметики и геометрии для учеников начальной школы.',
	},

	// Физика (дополнительные карточки)
	{
		id: 17,
		name: 'Карточки по физике ЕГЭ',
		price: 990,
		oldPrice: 1190,
		rating: 4.8,
		reviewCount: 142,
		imageSrc: '/images/products/physics-ege-cards.jpg',
		label: 'Скидка 15%',
		subject: 'Физика',
		grade: '11 класс (ЕГЭ)',
		cardType: 'Комбинированный',
		quantity: 5,
		slug: 'kartochki-po-fizike-ege',
		number_of_cards: 65,
		description:
			'Комбинированный набор карточек для подготовки к ЕГЭ по физике с формулами, законами и типовыми задачами.',
	},
	{
		id: 18,
		name: 'Карточки по физике 7-8 класс',
		price: 780,
		oldPrice: null,
		rating: 4.6,
		reviewCount: 89,
		imageSrc: '/images/products/physics-7-8-cards.jpg',
		label: null,
		subject: 'Физика',
		grade: '7-8 класс',
		cardType: 'Вопрос-ответ',
		quantity: 12,
		slug: 'kartochki-po-fizike-7-8-klass',
		number_of_cards: 45,
		description:
			'Карточки с вопросами и ответами по основам физики для учеников 7-8 классов.',
	},
	{
		id: 19,
		name: 'Карточки по физике 10-11 класс',
		price: 920,
		oldPrice: 1050,
		rating: 4.7,
		reviewCount: 112,
		imageSrc: '/images/products/physics-10-11-cards.jpg',
		label: 'Скидка 10%',
		subject: 'Физика',
		grade: '10-11 класс',
		cardType: 'Шпаргалки',
		quantity: 9,
		slug: 'kartochki-po-fizike-10-11-klass',
		number_of_cards: 55,
		description:
			'Шпаргалки по физике для учеников 10-11 классов с формулами и законами.',
	},

	// Русский язык (дополнительные карточки)
	{
		id: 20,
		name: 'Карточки по русскому языку ОГЭ',
		price: 750,
		oldPrice: 890,
		rating: 4.8,
		reviewCount: 128,
		imageSrc: '/images/products/russian-oge-cards.jpg',
		label: 'Скидка 15%',
		subject: 'Русский язык',
		grade: '9 класс (ОГЭ)',
		cardType: 'Комбинированный',
		quantity: 14,
		slug: 'kartochki-po-russkomu-yazyku-oge',
		number_of_cards: 50,
		description:
			'Комбинированный набор карточек для подготовки к ОГЭ по русскому языку.',
	},
	{
		id: 21,
		name: 'Карточки по русскому языку 5-7 класс',
		price: 690,
		oldPrice: null,
		rating: 4.6,
		reviewCount: 97,
		imageSrc: '/images/products/russian-5-7-cards.jpg',
		label: null,
		subject: 'Русский язык',
		grade: '5-7 класс',
		cardType: 'Вопрос-ответ',
		quantity: 11,
		slug: 'kartochki-po-russkomu-yazyku-5-7-klass',
		number_of_cards: 45,
		description:
			'Карточки с вопросами и ответами по русскому языку для учеников 5-7 классов.',
	},
	{
		id: 22,
		name: 'Карточки по русскому языку для начальной школы',
		price: 650,
		oldPrice: 780,
		rating: 4.9,
		reviewCount: 183,
		imageSrc: '/images/products/russian-primary-cards.jpg',
		label: 'Хит продаж',
		subject: 'Русский язык',
		grade: '1-4 класс',
		cardType: 'Вопрос-ответ',
		quantity: 22,
		slug: 'kartochki-po-russkomu-yazyku-dlya-nachalnoy-shkoly',
		number_of_cards: 40,
		description:
			'Карточки с правилами русского языка и орфографии для учеников начальной школы.',
	},

	// Биология (дополнительные карточки)
	{
		id: 23,
		name: 'Карточки по биологии ОГЭ',
		price: 880,
		oldPrice: 990,
		rating: 4.7,
		reviewCount: 105,
		imageSrc: '/images/products/biology-oge-cards.jpg',
		label: 'Скидка 10%',
		subject: 'Биология',
		grade: '9 класс (ОГЭ)',
		cardType: 'Комбинированный',
		quantity: 8,
		slug: 'kartochki-po-biologii-oge',
		number_of_cards: 55,
		description:
			'Комбинированный набор карточек для подготовки к ОГЭ по биологии.',
	},
	{
		id: 24,
		name: 'Карточки по биологии ЕГЭ',
		price: 950,
		oldPrice: 1150,
		rating: 4.8,
		reviewCount: 118,
		imageSrc: '/images/products/biology-ege-cards.jpg',
		label: 'Скидка 15%',
		subject: 'Биология',
		grade: '11 класс (ЕГЭ)',
		cardType: 'Шпаргалки',
		quantity: 4,
		slug: 'kartochki-po-biologii-ege',
		number_of_cards: 70,
		description:
			'Шпаргалки для подготовки к ЕГЭ по биологии с ключевыми понятиями и терминами.',
	},
	{
		id: 25,
		name: 'Карточки по анатомии человека',
		price: 920,
		oldPrice: null,
		rating: 4.9,
		reviewCount: 142,
		imageSrc: '/images/products/anatomy-cards.jpg',
		label: 'Новинка',
		subject: 'Биология',
		grade: '8-9 класс',
		cardType: 'Вопрос-ответ',
		quantity: 6,
		slug: 'kartochki-po-anatomii-cheloveka',
		number_of_cards: 60,
		description:
			'Карточки с вопросами и ответами по анатомии человека для учеников 8-9 классов.',
	},

	// Химия (дополнительные карточки)
	{
		id: 26,
		name: 'Карточки по химии ОГЭ',
		price: 890,
		oldPrice: 980,
		rating: 4.6,
		reviewCount: 87,
		imageSrc: '/images/products/chemistry-oge-cards.jpg',
		label: 'Скидка 10%',
		subject: 'Химия',
		grade: '9 класс (ОГЭ)',
		cardType: 'Комбинированный',
		quantity: 7,
		slug: 'kartochki-po-khimii-oge',
		number_of_cards: 50,
		description:
			'Комбинированный набор карточек для подготовки к ОГЭ по химии.',
	},
	{
		id: 27,
		name: 'Карточки по химии ЕГЭ',
		price: 980,
		oldPrice: 1150,
		rating: 4.8,
		reviewCount: 109,
		imageSrc: '/images/products/chemistry-ege-cards.jpg',
		label: 'Скидка 15%',
		subject: 'Химия',
		grade: '11 класс (ЕГЭ)',
		cardType: 'Шпаргалки',
		quantity: 3,
		slug: 'kartochki-po-khimii-ege',
		number_of_cards: 65,
		description:
			'Шпаргалки для подготовки к ЕГЭ по химии с формулами, реакциями и свойствами веществ.',
	},
	{
		id: 28,
		name: 'Карточки по органической химии',
		price: 920,
		oldPrice: null,
		rating: 4.7,
		reviewCount: 94,
		imageSrc: '/images/products/organic-chemistry-cards.jpg',
		label: null,
		subject: 'Химия',
		grade: '10-11 класс',
		cardType: 'Вопрос-ответ',
		quantity: 5,
		slug: 'kartochki-po-organicheskoy-khimii',
		number_of_cards: 55,
		description:
			'Карточки с вопросами и ответами по органической химии для учеников 10-11 классов.',
	},

	// История (дополнительные карточки)
	{
		id: 29,
		name: 'Карточки по истории ОГЭ',
		price: 850,
		oldPrice: 950,
		rating: 4.7,
		reviewCount: 112,
		imageSrc: '/images/products/history-oge-cards.jpg',
		label: 'Скидка 10%',
		subject: 'История',
		grade: '9 класс (ОГЭ)',
		cardType: 'Комбинированный',
		quantity: 6,
		slug: 'kartochki-po-istorii-oge',
		number_of_cards: 55,
		description:
			'Комбинированный набор карточек для подготовки к ОГЭ по истории.',
	},
	{
		id: 30,
		name: 'Карточки по истории России',
		price: 890,
		oldPrice: null,
		rating: 4.8,
		reviewCount: 127,
		imageSrc: '/images/products/russian-history-cards.jpg',
		label: 'Хит продаж',
		subject: 'История',
		grade: '6-9 класс',
		cardType: 'Вопрос-ответ',
		quantity: 11,
		slug: 'kartochki-po-istorii-rossii',
		number_of_cards: 60,
		description:
			'Карточки с вопросами и ответами по истории России с древнейших времен до наших дней.',
	},
	{
		id: 31,
		name: 'Карточки по всеобщей истории',
		price: 870,
		oldPrice: 950,
		rating: 4.5,
		reviewCount: 89,
		imageSrc: '/images/products/world-history-cards.jpg',
		label: 'Скидка 10%',
		subject: 'История',
		grade: '5-9 класс',
		cardType: 'Шпаргалки',
		quantity: 4,
		slug: 'kartochki-po-vseobshchey-istorii',
		number_of_cards: 65,
		description:
			'Шпаргалки по всеобщей истории с ключевыми датами, событиями и историческими личностями.',
	},

	// Английский язык (дополнительные карточки)
	{
		id: 32,
		name: 'Карточки по английскому языку ОГЭ',
		price: 880,
		oldPrice: 980,
		rating: 4.7,
		reviewCount: 104,
		imageSrc: '/images/products/english-oge-cards.jpg',
		label: 'Скидка 10%',
		subject: 'Английский язык',
		grade: '9 класс (ОГЭ)',
		cardType: 'Комбинированный',
		quantity: 8,
		slug: 'kartochki-po-angliyskomu-yazyku-oge',
		number_of_cards: 55,
		description:
			'Комбинированный набор карточек для подготовки к ОГЭ по английскому языку.',
	},
	{
		id: 33,
		name: 'Карточки по английскому языку ЕГЭ',
		price: 990,
		oldPrice: 1190,
		rating: 4.8,
		reviewCount: 138,
		imageSrc: '/images/products/english-ege-cards.jpg',
		label: 'Скидка 15%',
		subject: 'Английский язык',
		grade: '11 класс (ЕГЭ)',
		cardType: 'Шпаргалки',
		quantity: 5,
		slug: 'kartochki-po-angliyskomu-yazyku-ege',
		number_of_cards: 70,
		description:
			'Шпаргалки для подготовки к ЕГЭ по английскому языку с грамматикой и лексикой.',
	},
	{
		id: 34,
		name: 'Карточки по английской грамматике',
		price: 790,
		oldPrice: null,
		rating: 4.9,
		reviewCount: 156,
		imageSrc: '/images/products/english-grammar-cards.jpg',
		label: 'Хит продаж',
		subject: 'Английский язык',
		grade: '5-11 класс',
		cardType: 'Вопрос-ответ',
		quantity: 14,
		slug: 'kartochki-po-angliyskoy-grammatike',
		number_of_cards: 60,
		description:
			'Карточки с правилами английской грамматики, временами и конструкциями.',
	},

	// Литература (дополнительные карточки)
	{
		id: 35,
		name: 'Карточки по литературе ОГЭ',
		price: 820,
		oldPrice: 920,
		rating: 4.6,
		reviewCount: 91,
		imageSrc: '/images/products/literature-oge-cards.jpg',
		label: 'Скидка 10%',
		subject: 'Литература',
		grade: '9 класс (ОГЭ)',
		cardType: 'Комбинированный',
		quantity: 7,
		slug: 'kartochki-po-literature-oge',
		number_of_cards: 50,
		description:
			'Комбинированный набор карточек для подготовки к ОГЭ по литературе.',
	},
	{
		id: 36,
		name: 'Карточки по литературе ЕГЭ',
		price: 890,
		oldPrice: 1050,
		rating: 4.8,
		reviewCount: 124,
		imageSrc: '/images/products/literature-ege-cards.jpg',
		label: 'Скидка 15%',
		subject: 'Литература',
		grade: '11 класс (ЕГЭ)',
		cardType: 'Шпаргалки',
		quantity: 4,
		slug: 'kartochki-po-literature-ege',
		number_of_cards: 65,
		description:
			'Шпаргалки для подготовки к ЕГЭ по литературе с кратким содержанием произведений и анализом.',
	},
	{
		id: 37,
		name: 'Карточки по зарубежной литературе',
		price: 840,
		oldPrice: null,
		rating: 4.7,
		reviewCount: 103,
		imageSrc: '/images/products/foreign-literature-cards.jpg',
		label: 'Новинка',
		subject: 'Литература',
		grade: '8-11 класс',
		cardType: 'Вопрос-ответ',
		quantity: 9,
		slug: 'kartochki-po-zarubezhnoy-literature',
		number_of_cards: 55,
		description:
			'Карточки с вопросами и ответами по зарубежной литературе, включая анализ произведений и биографии авторов.',
	},

	// География (дополнительные карточки)
	{
		id: 38,
		name: 'Карточки по географии ОГЭ',
		price: 780,
		oldPrice: 880,
		rating: 4.6,
		reviewCount: 89,
		imageSrc: '/images/products/geography-oge-cards.jpg',
		label: 'Скидка 10%',
		subject: 'География',
		grade: '9 класс (ОГЭ)',
		cardType: 'Комбинированный',
		quantity: 6,
		slug: 'kartochki-po-geografii-oge',
		number_of_cards: 50,
		description:
			'Комбинированный набор карточек для подготовки к ОГЭ по географии.',
	},
	{
		id: 39,
		name: 'Карточки по географии ЕГЭ',
		price: 850,
		oldPrice: 990,
		rating: 4.7,
		reviewCount: 97,
		imageSrc: '/images/products/geography-ege-cards.jpg',
		label: 'Скидка 15%',
		subject: 'География',
		grade: '11 класс (ЕГЭ)',
		cardType: 'Шпаргалки',
		quantity: 3,
		slug: 'kartochki-po-geografii-ege',
		number_of_cards: 60,
		description:
			'Шпаргалки для подготовки к ЕГЭ по географии с картами, таблицами и статистическими данными.',
	},
	{
		id: 40,
		name: 'Карточки по экономической географии',
		price: 820,
		oldPrice: null,
		rating: 4.5,
		reviewCount: 82,
		imageSrc: '/images/products/economic-geography-cards.jpg',
		label: null,
		subject: 'География',
		grade: '10-11 класс',
		cardType: 'Вопрос-ответ',
		quantity: 8,
		slug: 'kartochki-po-ekonomicheskoy-geografii',
		number_of_cards: 45,
		description:
			'Карточки с вопросами и ответами по экономической географии России и мира.',
	},

	// Обществознание (дополнительные карточки)
	{
		id: 41,
		name: 'Карточки по обществознанию ЕГЭ',
		price: 920,
		oldPrice: 1090,
		rating: 4.9,
		reviewCount: 145,
		imageSrc: '/images/products/society-ege-cards.jpg',
		label: 'Хит продаж',
		subject: 'Обществознание',
		grade: '11 класс (ЕГЭ)',
		cardType: 'Комбинированный',
		quantity: 7,
		slug: 'kartochki-po-obshchestvoznaniyu-ege',
		number_of_cards: 70,
		description:
			'Комбинированный набор карточек для подготовки к ЕГЭ по обществознанию со всеми разделами курса.',
	},
	{
		id: 42,
		name: 'Карточки по праву',
		price: 850,
		oldPrice: null,
		rating: 4.7,
		reviewCount: 96,
		imageSrc: '/images/products/law-cards.jpg',
		label: 'Новинка',
		subject: 'Обществознание',
		grade: '9-11 класс',
		cardType: 'Вопрос-ответ',
		quantity: 5,
		slug: 'kartochki-po-pravu',
		number_of_cards: 50,
		description:
			'Карточки с вопросами и ответами по основам права для учеников 9-11 классов.',
	},
	{
		id: 43,
		name: 'Карточки по экономике',
		price: 870,
		oldPrice: 950,
		rating: 4.6,
		reviewCount: 89,
		imageSrc: '/images/products/economics-cards.jpg',
		label: 'Скидка 10%',
		subject: 'Обществознание',
		grade: '9-11 класс',
		cardType: 'Шпаргалки',
		quantity: 4,
		slug: 'kartochki-po-ekonomike',
		number_of_cards: 45,
		description:
			'Шпаргалки по экономике с основными терминами, графиками и формулами.',
	},

	// Информатика (дополнительные карточки)
	{
		id: 44,
		name: 'Карточки по информатике ОГЭ',
		price: 830,
		oldPrice: 920,
		rating: 4.7,
		reviewCount: 108,
		imageSrc: '/images/products/informatics-oge-cards.jpg',
		label: 'Скидка 10%',
		subject: 'Информатика',
		grade: '9 класс (ОГЭ)',
		cardType: 'Комбинированный',
		quantity: 7,
		slug: 'kartochki-po-informatike-oge',
		number_of_cards: 50,
		description:
			'Комбинированный набор карточек для подготовки к ОГЭ по информатике.',
	},
	{
		id: 45,
		name: 'Карточки по информатике ЕГЭ',
		price: 950,
		oldPrice: 1090,
		rating: 4.8,
		reviewCount: 132,
		imageSrc: '/images/products/informatics-ege-cards.jpg',
		label: 'Скидка 10%',
		subject: 'Информатика',
		grade: '11 класс (ЕГЭ)',
		cardType: 'Шпаргалки',
		quantity: 3,
		slug: 'kartochki-po-informatike-ege',
		number_of_cards: 65,
		description:
			'Шпаргалки для подготовки к ЕГЭ по информатике с алгоритмами и примерами кода.',
	},
	{
		id: 46,
		name: 'Карточки по программированию',
		price: 890,
		oldPrice: null,
		rating: 4.9,
		reviewCount: 124,
		imageSrc: '/images/products/programming-cards.jpg',
		label: 'Хит продаж',
		subject: 'Информатика',
		grade: '8-11 класс',
		cardType: 'Вопрос-ответ',
		quantity: 9,
		slug: 'kartochki-po-programmirovaniyu',
		number_of_cards: 55,
		description:
			'Карточки с вопросами и ответами по основам программирования на Python и C++.',
	},

	// Геометрия (дополнительные карточки)
	{
		id: 47,
		name: 'Карточки по планиметрии',
		price: 780,
		oldPrice: 880,
		rating: 4.7,
		reviewCount: 105,
		imageSrc: '/images/products/planimetry-cards.jpg',
		label: 'Скидка 10%',
		subject: 'Геометрия',
		grade: '7-9 класс',
		cardType: 'Шпаргалки',
		quantity: 6,
		slug: 'kartochki-po-planimetrii',
		number_of_cards: 45,
		description:
			'Шпаргалки по планиметрии с формулами, теоремами и методами решения задач.',
	},
	{
		id: 48,
		name: 'Карточки по стереометрии',
		price: 820,
		oldPrice: null,
		rating: 4.6,
		reviewCount: 92,
		imageSrc: '/images/products/stereometry-cards.jpg',
		label: null,
		subject: 'Геометрия',
		grade: '10-11 класс',
		cardType: 'Вопрос-ответ',
		quantity: 4,
		slug: 'kartochki-po-stereometrii',
		number_of_cards: 40,
		description:
			'Карточки с вопросами и ответами по стереометрии с формулами и методами решения задач.',
	},
	{
		id: 49,
		name: 'Карточки по геометрии ЕГЭ',
		price: 890,
		oldPrice: 990,
		rating: 4.8,
		reviewCount: 118,
		imageSrc: '/images/products/geometry-ege-cards.jpg',
		label: 'Скидка 10%',
		subject: 'Геометрия',
		grade: '11 класс (ЕГЭ)',
		cardType: 'Комбинированный',
		quantity: 7,
		slug: 'kartochki-po-geometrii-ege',
		number_of_cards: 55,
		description:
			'Комбинированный набор карточек для подготовки к геометрическим задачам ЕГЭ по математике.',
	},

	// Новые предметы

	// Астрономия
	{
		id: 50,
		name: 'Карточки по астрономии',
		price: 850,
		oldPrice: null,
		rating: 4.7,
		reviewCount: 86,
		imageSrc: '/images/products/astronomy-cards.jpg',
		label: 'Новинка',
		subject: 'Астрономия',
		grade: '10-11 класс',
		cardType: 'Вопрос-ответ',
		quantity: 12,
		slug: 'kartochki-po-astronomii',
		number_of_cards: 45,
		description:
			'Карточки с вопросами и ответами по основам астрономии для учеников 10-11 классов.',
	},
	{
		id: 51,
		name: 'Карточки по солнечной системе',
		price: 790,
		oldPrice: 890,
		rating: 4.8,
		reviewCount: 94,
		imageSrc: '/images/products/solar-system-cards.jpg',
		label: 'Скидка 10%',
		subject: 'Астрономия',
		grade: '5-9 класс',
		cardType: 'Шпаргалки',
		quantity: 8,
		slug: 'kartochki-po-solnechnoy-sisteme',
		number_of_cards: 40,
		description:
			'Шпаргалки с информацией о планетах, звездах и других объектах солнечной системы.',
	},

	// ОБЖ
	{
		id: 52,
		name: 'Карточки по основам безопасности жизнедеятельности',
		price: 720,
		oldPrice: null,
		rating: 4.5,
		reviewCount: 78,
		imageSrc: '/images/products/obzh-cards.jpg',
		label: null,
		subject: 'ОБЖ',
		grade: '5-9 класс',
		cardType: 'Вопрос-ответ',
		quantity: 15,
		slug: 'kartochki-po-obzh',
		number_of_cards: 40,
		description:
			'Карточки с вопросами и ответами по основам безопасности жизнедеятельности для учеников 5-9 классов.',
	},
	{
		id: 53,
		name: 'Карточки по первой помощи',
		price: 690,
		oldPrice: 790,
		rating: 4.9,
		reviewCount: 135,
		imageSrc: '/images/products/first-aid-cards.jpg',
		label: 'Хит продаж',
		subject: 'ОБЖ',
		grade: '5-11 класс',
		cardType: 'Шпаргалки',
		quantity: 18,
		slug: 'kartochki-po-pervoy-pomoshchi',
		number_of_cards: 35,
		description:
			'Шпаргалки с правилами оказания первой помощи в различных ситуациях.',
	},

	// Немецкий язык
	{
		id: 54,
		name: 'Карточки по немецкому языку',
		price: 820,
		oldPrice: null,
		rating: 4.6,
		reviewCount: 82,
		imageSrc: '/images/products/german-cards.jpg',
		label: 'Новинка',
		subject: 'Немецкий язык',
		grade: '5-9 класс',
		cardType: 'Вопрос-ответ',
		quantity: 10,
		slug: 'kartochki-po-nemetskomu-yazyku',
		number_of_cards: 50,
		description:
			'Карточки с вопросами и ответами по немецкой грамматике и лексике для учеников 5-9 классов.',
	},
	{
		id: 55,
		name: 'Карточки по немецкому языку ЕГЭ',
		price: 940,
		oldPrice: 1050,
		rating: 4.7,
		reviewCount: 75,
		imageSrc: '/images/products/german-ege-cards.jpg',
		label: 'Скидка 10%',
		subject: 'Немецкий язык',
		grade: '11 класс (ЕГЭ)',
		cardType: 'Комбинированный',
		quantity: 5,
		slug: 'kartochki-po-nemetskomu-yazyku-ege',
		number_of_cards: 65,
		description:
			'Комбинированный набор карточек для подготовки к ЕГЭ по немецкому языку.',
	},

	// Французский язык
	{
		id: 56,
		name: 'Карточки по французскому языку',
		price: 840,
		oldPrice: null,
		rating: 4.5,
		reviewCount: 68,
		imageSrc: '/images/products/french-cards.jpg',
		label: 'Новинка',
		subject: 'Французский язык',
		grade: '5-9 класс',
		cardType: 'Вопрос-ответ',
		quantity: 7,
		slug: 'kartochki-po-frantsuzskomu-yazyku',
		number_of_cards: 45,
		description:
			'Карточки с вопросами и ответами по французской грамматике и лексике для учеников 5-9 классов.',
	},
	{
		id: 57,
		name: 'Карточки по французскому языку ЕГЭ',
		price: 950,
		oldPrice: 1080,
		rating: 4.6,
		reviewCount: 62,
		imageSrc: '/images/products/french-ege-cards.jpg',
		label: 'Скидка 10%',
		subject: 'Французский язык',
		grade: '11 класс (ЕГЭ)',
		cardType: 'Комбинированный',
		quantity: 4,
		slug: 'kartochki-po-frantsuzskomu-yazyku-ege',
		number_of_cards: 60,
		description:
			'Комбинированный набор карточек для подготовки к ЕГЭ по французскому языку.',
	},

	// Испанский язык
	{
		id: 58,
		name: 'Карточки по испанскому языку',
		price: 830,
		oldPrice: null,
		rating: 4.6,
		reviewCount: 71,
		imageSrc: '/images/products/spanish-cards.jpg',
		label: 'Новинка',
		subject: 'Испанский язык',
		grade: '5-9 класс',
		cardType: 'Вопрос-ответ',
		quantity: 6,
		slug: 'kartochki-po-ispanskomu-yazyku',
		number_of_cards: 45,
		description:
			'Карточки с вопросами и ответами по испанской грамматике и лексике для учеников 5-9 классов.',
	},
	{
		id: 59,
		name: 'Карточки по испанскому языку ЕГЭ',
		price: 940,
		oldPrice: 1060,
		rating: 4.7,
		reviewCount: 58,
		imageSrc: '/images/products/spanish-ege-cards.jpg',
		label: 'Скидка 10%',
		subject: 'Испанский язык',
		grade: '11 класс (ЕГЭ)',
		cardType: 'Комбинированный',
		quantity: 3,
		slug: 'kartochki-po-ispanskomu-yazyku-ege',
		number_of_cards: 55,
		description:
			'Комбинированный набор карточек для подготовки к ЕГЭ по испанскому языку.',
	},

	// МХК (Мировая художественная культура)
	{
		id: 60,
		name: 'Карточки по мировой художественной культуре',
		price: 860,
		oldPrice: null,
		rating: 4.7,
		reviewCount: 84,
		imageSrc: '/images/products/art-culture-cards.jpg',
		label: 'Новинка',
		subject: 'МХК',
		grade: '9-11 класс',
		cardType: 'Вопрос-ответ',
		quantity: 9,
		slug: 'kartochki-po-mirovoy-khudozhestvennoy-kulture',
		number_of_cards: 55,
		description:
			'Карточки с вопросами и ответами по мировой художественной культуре с описанием стилей, направлений и известных произведений искусства.',
	},
	{
		id: 61,
		name: 'Карточки по истории искусства',
		price: 890,
		oldPrice: 980,
		rating: 4.8,
		reviewCount: 76,
		imageSrc: '/images/products/art-history-cards.jpg',
		label: 'Скидка 10%',
		subject: 'МХК',
		grade: '8-11 класс',
		cardType: 'Шпаргалки',
		quantity: 5,
		slug: 'kartochki-po-istorii-iskusstva',
		number_of_cards: 50,
		description:
			'Шпаргалки по истории искусства с информацией о художниках, архитекторах и их произведениях.',
	},

	// Экология
	{
		id: 62,
		name: 'Карточки по экологии',
		price: 780,
		oldPrice: null,
		rating: 4.6,
		reviewCount: 79,
		imageSrc: '/images/products/ecology-cards.jpg',
		label: 'Новинка',
		subject: 'Экология',
		grade: '6-9 класс',
		cardType: 'Вопрос-ответ',
		quantity: 11,
		slug: 'kartochki-po-ekologii',
		number_of_cards: 45,
		description:
			'Карточки с вопросами и ответами по основам экологии для учеников 6-9 классов.',
	},
	{
		id: 63,
		name: 'Карточки по охране окружающей среды',
		price: 750,
		oldPrice: 850,
		rating: 4.7,
		reviewCount: 82,
		imageSrc: '/images/products/environment-cards.jpg',
		label: 'Скидка 10%',
		subject: 'Экология',
		grade: '5-11 класс',
		cardType: 'Шпаргалки',
		quantity: 8,
		slug: 'kartochki-po-okhrane-okruzhayushchey-sredy',
		number_of_cards: 40,
		description:
			'Шпаргалки с информацией об экологических проблемах и способах их решения.',
	},

	// Технология
	{
		id: 64,
		name: 'Карточки по технологии для мальчиков',
		price: 720,
		oldPrice: null,
		rating: 4.5,
		reviewCount: 73,
		imageSrc: '/images/products/tech-boys-cards.jpg',
		label: null,
		subject: 'Технология',
		grade: '5-8 класс',
		cardType: 'Вопрос-ответ',
		quantity: 14,
		slug: 'kartochki-po-tekhnologii-dlya-malchikov',
		number_of_cards: 40,
		description:
			'Карточки с вопросами и ответами по технологии для мальчиков, включая работу с различными материалами и инструментами.',
	},
	{
		id: 65,
		name: 'Карточки по технологии для девочек',
		price: 720,
		oldPrice: null,
		rating: 4.6,
		reviewCount: 81,
		imageSrc: '/images/products/tech-girls-cards.jpg',
		label: null,
		subject: 'Технология',
		grade: '5-8 класс',
		cardType: 'Вопрос-ответ',
		quantity: 13,
		slug: 'kartochki-po-tekhnologii-dlya-devochek',
		number_of_cards: 40,
		description:
			'Карточки с вопросами и ответами по технологии для девочек, включая кулинарию, шитье и ведение домашнего хозяйства.',
	},

	// Черчение
	{
		id: 66,
		name: 'Карточки по черчению',
		price: 780,
		oldPrice: null,
		rating: 4.5,
		reviewCount: 68,
		imageSrc: '/images/products/drawing-cards.jpg',
		label: 'Новинка',
		subject: 'Черчение',
		grade: '8-9 класс',
		cardType: 'Вопрос-ответ',
		quantity: 9,
		slug: 'kartochki-po-chercheniyu',
		number_of_cards: 45,
		description:
			'Карточки с вопросами и ответами по основам черчения с правилами оформления чертежей.',
	},
	{
		id: 67,
		name: 'Карточки по техническому черчению',
		price: 820,
		oldPrice: 890,
		rating: 4.6,
		reviewCount: 71,
		imageSrc: '/images/products/technical-drawing-cards.jpg',
		label: 'Скидка 10%',
		subject: 'Черчение',
		grade: '9-11 класс',
		cardType: 'Шпаргалки',
		quantity: 6,
		slug: 'kartochki-po-tekhnicheskomu-chercheniyu',
		number_of_cards: 40,
		description:
			'Шпаргалки по техническому черчению с правилами оформления чертежей и проекций.',
	},

	// Окружающий мир (для начальной школы)
	{
		id: 68,
		name: 'Карточки по окружающему миру',
		price: 650,
		oldPrice: null,
		rating: 4.8,
		reviewCount: 145,
		imageSrc: '/images/products/world-around-cards.jpg',
		label: 'Хит продаж',
		subject: 'Окружающий мир',
		grade: '1-4 класс',
		cardType: 'Вопрос-ответ',
		quantity: 22,
		slug: 'kartochki-po-okruzhayushchemu-miru',
		number_of_cards: 40,
		description:
			'Карточки с вопросами и ответами по окружающему миру для учеников начальной школы.',
	},
	{
		id: 69,
		name: 'Карточки по природоведению',
		price: 620,
		oldPrice: 720,
		rating: 4.9,
		reviewCount: 158,
		imageSrc: '/images/products/nature-study-cards.jpg',
		label: 'Скидка 15%',
		subject: 'Окружающий мир',
		grade: '1-4 класс',
		cardType: 'Комбинированный',
		quantity: 18,
		slug: 'kartochki-po-prirodovedeniyu',
		number_of_cards: 35,
		description:
			'Комбинированный набор карточек по природоведению для учеников начальной школы с иллюстрациями растений, животных и природных явлений.',
	},

	// Китайский язык
	{
		id: 70,
		name: 'Карточки по китайскому языку',
		price: 950,
		oldPrice: null,
		rating: 4.6,
		reviewCount: 64,
		imageSrc: '/images/products/chinese-cards.jpg',
		label: 'Новинка',
		subject: 'Китайский язык',
		grade: '5-9 класс',
		cardType: 'Вопрос-ответ',
		quantity: 7,
		slug: 'kartochki-po-kitayskomu-yazyku',
		number_of_cards: 50,
		description:
			'Карточки с вопросами и ответами по китайской грамматике и лексике для учеников 5-9 классов.',
	},
	{
		id: 71,
		name: 'Карточки по китайскому языку ЕГЭ',
		price: 1050,
		oldPrice: 1190,
		rating: 4.7,
		reviewCount: 57,
		imageSrc: '/images/products/chinese-ege-cards.jpg',
		label: 'Скидка 10%',
		subject: 'Китайский язык',
		grade: '11 класс (ЕГЭ)',
		cardType: 'Комбинированный',
		quantity: 4,
		slug: 'kartochki-po-kitayskomu-yazyku-ege',
		number_of_cards: 65,
		description:
			'Комбинированный набор карточек для подготовки к ЕГЭ по китайскому языку.',
	},
]

export default productMockData
