// src/lib/mock-data.js (обновленная версия с добавлением поля slug)
const productMockData = [
	{
		id: 1,
		name: 'Карточки по математике 5-6 класс',
		price: 890,
		oldPrice: 1190,
		rating: 4.8,
		reviewCount: 124,
		imageSrc: '/images/products/math-cards.jpg',
		label: 'Хит продаж',
		subject: 'Математика',
		grade: '5-6 класс',
		cardType: 'Вопрос-ответ',
		quantity: 15,
		slug: 'kartochki-po-matematike-5-6-klass',
	},
	{
		id: 2,
		name: 'Карточки по физике ОГЭ',
		price: 950,
		oldPrice: null,
		rating: 4.5,
		reviewCount: 87,
		imageSrc: '/images/products/physics-cards.jpg',
		label: 'Новинка',
		subject: 'Физика',
		grade: '9 класс (ОГЭ)',
		cardType: 'Шпаргалки',
		quantity: 8,
		slug: 'kartochki-po-fizike-oge',
	},
	{
		id: 3,
		name: 'Карточки по русскому языку ЕГЭ',
		price: 790,
		oldPrice: 990,
		rating: 4.7,
		reviewCount: 156,
		imageSrc: '/images/products/russian-cards.jpg',
		label: 'Скидка 20%',
		subject: 'Русский язык',
		grade: '11 класс (ЕГЭ)',
		cardType: 'Комбинированный',
		quantity: 12,
		slug: 'kartochki-po-russkomu-yazyku-ege',
	},
	{
		id: 4,
		name: 'Карточки по биологии 7-8 класс',
		price: 850,
		oldPrice: 1050,
		rating: 4.6,
		reviewCount: 92,
		imageSrc: '/images/products/biology-cards.jpg',
		label: null,
		subject: 'Биология',
		grade: '7-8 класс',
		cardType: 'Вопрос-ответ',
		quantity: 5,
		slug: 'kartochki-po-biologii-7-8-klass',
	},
	{
		id: 5,
		name: 'Карточки по химии 8-9 класс',
		price: 920,
		oldPrice: null,
		rating: 4.4,
		reviewCount: 78,
		imageSrc: '/images/products/chemistry-cards.jpg',
		label: null,
		subject: 'Химия',
		grade: '8-9 класс',
		cardType: 'Шпаргалки',
		quantity: 2,
		slug: 'kartochki-po-khimii-8-9-klass',
	},
	{
		id: 6,
		name: 'Карточки по истории ЕГЭ',
		price: 990,
		oldPrice: 1290,
		rating: 4.9,
		reviewCount: 142,
		imageSrc: '/images/products/history-cards.jpg',
		label: 'Топ продаж',
		subject: 'История',
		grade: '11 класс (ЕГЭ)',
		cardType: 'Комбинированный',
		quantity: 0,
		slug: 'kartochki-po-istorii-ege',
	},
	{
		id: 7,
		name: 'Карточки по английскому языку 5-7 класс',
		price: 780,
		oldPrice: 920,
		rating: 4.7,
		reviewCount: 112,
		imageSrc: '/images/products/english-cards.jpg',
		label: 'Скидка 15%',
		subject: 'Английский язык',
		grade: '5-6 класс',
		cardType: 'Вопрос-ответ',
		quantity: 10,
		slug: 'kartochki-po-angliyskomu-yazyku-5-7-klass',
	},
	{
		id: 8,
		name: 'Карточки по литературе 10-11 класс',
		price: 860,
		oldPrice: null,
		rating: 4.6,
		reviewCount: 94,
		imageSrc: '/images/products/literature-cards.jpg',
		label: null,
		subject: 'Литература',
		grade: '10-11 класс',
		cardType: 'Шпаргалки',
		quantity: 7,
		slug: 'kartochki-po-literature-10-11-klass',
	},
	{
		id: 9,
		name: 'Карточки по географии 6-7 класс',
		price: 760,
		oldPrice: 890,
		rating: 4.5,
		reviewCount: 82,
		imageSrc: '/images/products/geography-cards.jpg',
		label: null,
		subject: 'География',
		grade: '7-8 класс',
		cardType: 'Вопрос-ответ',
		quantity: 4,
		slug: 'kartochki-po-geografii-6-7-klass',
	},
	{
		id: 10,
		name: 'Карточки по обществознанию ОГЭ',
		price: 880,
		oldPrice: 1080,
		rating: 4.8,
		reviewCount: 136,
		imageSrc: '/images/products/society-cards.jpg',
		label: 'Хит продаж',
		subject: 'Обществознание',
		grade: '9 класс (ОГЭ)',
		cardType: 'Комбинированный',
		quantity: 9,
		slug: 'kartochki-po-obshchestvoznaniyu-oge',
	},
	{
		id: 11,
		name: 'Карточки по информатике 8-9 класс',
		price: 840,
		oldPrice: null,
		rating: 4.6,
		reviewCount: 98,
		imageSrc: '/images/products/informatics-cards.jpg',
		label: 'Новинка',
		subject: 'Информатика',
		grade: '8-9 класс',
		cardType: 'Шпаргалки',
		quantity: 1,
		slug: 'kartochki-po-informatike-8-9-klass',
	},
	{
		id: 12,
		name: 'Карточки по геометрии 7-9 класс',
		price: 820,
		oldPrice: 950,
		rating: 4.7,
		reviewCount: 108,
		imageSrc: '/images/products/geometry-cards.jpg',
		label: 'Скидка 15%',
		subject: 'Геометрия',
		grade: '8-9 класс',
		cardType: 'Вопрос-ответ',
		quantity: 0,
		slug: 'kartochki-po-geometrii-7-9-klass',
	},
]

export default productMockData
