name: mat-focus-base

version: '3'

services:
  db:
    image: postgres:16-alpine
    volumes:
      - db_data:/var/lib/postgresql/data
    networks:
      - backend
    restart: always
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U $$POSTGRES_USER" ]
      interval: 30s
      timeout: 10s
      retries: 3

  api:
    networks:
      - frontend
      - backend
    depends_on:
      db:
        condition: service_healthy
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:1337/_health" ]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    restart: always

  client:
    networks:
      - frontend
    restart: always


networks:
  frontend:
    driver: bridge
  backend:
    driver: bridge

volumes:
  db_data:
